### ISSUE TITLE
missing install notes

### ISSUE THREAD

**Issue by radiovisual** [pjeby/gulpsmith#12]
It was easy to guess that `$ npm install gulpsmith` would have worked to get gulpsmith into my project, and I found the project on npm to confirm, but it would be nice to see the install notes on your project's `Readme.md` :

```sh
$ npm install --save gulpsmith
```

**Comment by pjeby** [comment]
I'm wondering how you found the project, since as far as I know, all metalsmith plugins *and* all gulp plugins are installed via npm.  In addition, the first link at the top of the project's github page is to the npm page.  So I don't see a need to change this at the present time.
