### ISSUE TITLE
Misleading typo in Readme?

### ISSUE THREAD

**Issue by radiovisual** [pjeby/gulpsmith#13]
In [this section of your Readme](https://github.com/pjeby/gulpsmith#front-matter-and-file-properties), you have this following phrase:

>> Unlike Metalsmith, Gulp doesn't read YAML front matter by default. So if you want the front matter to be available in **Metalsmith**...

But I think it is meant to be read:

>> Unlike Metalsmith, Gulp doesn't read YAML front matter by default. So if you want the front matter to be available in **Gulp**...

**Comment by pjeby** [comment]
It means exactly what it says: if you are using Metalsmith from Gulp, then the front matter will not be available in *Metalsmith* unless you load it in Gulp.  It's also true that it won't be available in Gulp, but that's entirely beside the point.  Metalsmith plugins won't work correctly without the front matter, and that is what the point here is.
