### ISSUE TITLE
peerDependencies requirements

### ISSUE THREAD

**Issue by robmcguinness** [pjeby/gulpsmith#9]
Trying to upgrade Metalsmith to 2.x and I'm getting:

```bash
npm ERR! peerinvalid The package metalsmith does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulpsmith@0.5.3 wants metalsmith@^0.10||^0.11||^1.0.0
```

https://github.com/pjeby/gulpsmith/blob/3dd992e0158fd0e5e7349af52a085818ee924caa/package.json#L15

I think 2.x simply removed Node 10 support and should be compatible with the gulpsmith module.

**Comment by pjeby** [comment]
Ok, I've updated package.json in 0.5.4; you should be good to go.
